version: '3'

services:
  app:
    container_name: recipes-api
    restart: always
    build: .
    command: npm start
    environment:
      RECIPE_PUPPY_API_URL: 'http://www.recipepuppy.com/api'
      GIF_PUPPY_API_URL: 'http://api.giphy.com/v1/gifs/search'
      GIF_API_KEY: 'hpeG8DPD0Jo2yPSIc15t03bPa5r7mw7C'
    ports:
      - '7777:3000'
