version: '3'

services:
  app:
    container_name: recipes-api
    restart: always
    build: .
    command: npm start
    environment:
      RECIPE_PUPPY_API_URL: ${RECIPE_PUPPY_API_URL}
      GIF_PUPPY_API_URL: ${GIF_PUPPY_API_URL}
      GIF_API_KEY: ${GIF_API_KEY}
      GIF_NOT_FOUND_URL: ${GIF_NOT_FOUND_URL}
    ports:
      - ${EXPOSED_PORT}:${PORT}
    volumes:
      - .:/usr/app
